// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WorldwideEarthquakes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("earthquakes_LastUpdated")]
        public long EarthquakesLastUpdated { get; set; }

        [JsonProperty("earthquakes_LastHour")]
        public long EarthquakesLastHour { get; set; }

        [JsonProperty("earthquakes")]
        public Earthquake[] Earthquakes { get; set; }
    }

    public partial class Earthquake
    {
        [JsonProperty("mag")]
        public double Mag { get; set; }

        [JsonProperty("place")]
        public string Place { get; set; }

        [JsonProperty("time")]
        public long Time { get; set; }

        [JsonProperty("status")]
        public Status Status { get; set; }

        [JsonProperty("tsunami")]
        public long Tsunami { get; set; }

        [JsonProperty("sig")]
        public long Sig { get; set; }

        [JsonProperty("net")]
        public string Net { get; set; }

        [JsonProperty("types")]
        public string Types { get; set; }

        [JsonProperty("nst", NullValueHandling = NullValueHandling.Ignore)]
        public long? Nst { get; set; }

        [JsonProperty("dmin", NullValueHandling = NullValueHandling.Ignore)]
        public double? Dmin { get; set; }

        [JsonProperty("rms")]
        public double Rms { get; set; }

        [JsonProperty("gap", NullValueHandling = NullValueHandling.Ignore)]
        public double? Gap { get; set; }

        [JsonProperty("magType")]
        public MagType MagType { get; set; }

        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("coordinates")]
        public double[] Coordinates { get; set; }
    }

    public enum MagType { Md, Ml };

    public enum Status { Automatic, Reviewed };

    public enum TypeEnum { Earthquake };
}
