// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WorldwideEarthquakes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("earthquakes_LastUpdated")]
        public DateTimeOffset? EarthquakesLastUpdated { get; set; }

        [JsonProperty("earthquakes_LastHour")]
        public long? EarthquakesLastHour { get; set; }

        [JsonProperty("count24h")]
        public long? Count24H { get; set; }

        [JsonProperty("largestMagnitude24h")]
        public double? LargestMagnitude24H { get; set; }

        [JsonProperty("avgMagnitude24h")]
        public double? AvgMagnitude24H { get; set; }

        [JsonProperty("earthquakes")]
        public Earthquake[] Earthquakes { get; set; }
    }

    public partial class Earthquake
    {
        [JsonProperty("mag")]
        public double? Mag { get; set; }

        [JsonProperty("place")]
        public string Place { get; set; }

        [JsonProperty("time")]
        public long? Time { get; set; }

        [JsonProperty("felt")]
        public long? Felt { get; set; }

        [JsonProperty("cdi")]
        public double? Cdi { get; set; }

        [JsonProperty("mmi")]
        public double? Mmi { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("tsunami")]
        public long? Tsunami { get; set; }

        [JsonProperty("sig")]
        public long? Sig { get; set; }

        [JsonProperty("net")]
        public string Net { get; set; }

        [JsonProperty("types")]
        public string Types { get; set; }

        [JsonProperty("nst")]
        public long? Nst { get; set; }

        [JsonProperty("dmin")]
        public double? Dmin { get; set; }

        [JsonProperty("rms")]
        public double? Rms { get; set; }

        [JsonProperty("gap")]
        public long? Gap { get; set; }

        [JsonProperty("magType")]
        public string MagType { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("coordinates")]
        public double?[] Coordinates { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
